// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWXi5fH170LK9VZZRun3brqN463E90if4',
    appId: '1:222644583887:web:76ab3e5ea801c4c0ef66ba',
    messagingSenderId: '222644583887',
    projectId: 'flutter-firebase-7580f',
    authDomain: 'flutter-firebase-7580f.firebaseapp.com',
    storageBucket: 'flutter-firebase-7580f.firebasestorage.app',
    measurementId: 'G-VSLKQ71KY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX0dRhBY72ej9_XxdV6auroL2mSeO4zVM',
    appId: '1:222644583887:android:d704fb1912fa1a30ef66ba',
    messagingSenderId: '222644583887',
    projectId: 'flutter-firebase-7580f',
    storageBucket: 'flutter-firebase-7580f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9_b0E6qNW4vTWc7Ok4Wz4vg9XBthdho',
    appId: '1:222644583887:ios:2883bcd44d7c6c77ef66ba',
    messagingSenderId: '222644583887',
    projectId: 'flutter-firebase-7580f',
    storageBucket: 'flutter-firebase-7580f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9_b0E6qNW4vTWc7Ok4Wz4vg9XBthdho',
    appId: '1:222644583887:ios:2883bcd44d7c6c77ef66ba',
    messagingSenderId: '222644583887',
    projectId: 'flutter-firebase-7580f',
    storageBucket: 'flutter-firebase-7580f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWXi5fH170LK9VZZRun3brqN463E90if4',
    appId: '1:222644583887:web:b7db56127f0c3d1bef66ba',
    messagingSenderId: '222644583887',
    projectId: 'flutter-firebase-7580f',
    authDomain: 'flutter-firebase-7580f.firebaseapp.com',
    storageBucket: 'flutter-firebase-7580f.firebasestorage.app',
    measurementId: 'G-WWKEPM21E2',
  );
}
